### ISSUE TITLE
Is there any plan to support GHS toolchain?

### ISSUE THREAD

**Issue by zhangshengping** [mikisama/FreeRTOS_RH850_GCC#1]
Is there any plan to support GHS toolchain?
GHS's asm code and link scripts are different from IAR and CCRH. Is there any plan to support it?

**Comment by mikisama** [comment]
> Is there any plan to support GHS toolchain? GHS's asm code and link scripts are different from IAR and CCRH. Is there any plan to support it?

I plan to do this, however GHS doesn't seem to offer an evaluation version so I can't work on. 😂
