### ISSUE TITLE
The readme should mention that the other cmake files should be used in case you build not for GCC

### ISSUE THREAD

**Issue by AntonKukoba1** [mikisama/FreeRTOS_RH850_GCC#2]
First of all it thank you for the sample. But it wasn't obvious for me that it's for building under windows only. And it wasn't clear that to build for ccrh I need to use ccrh.cmake, instead of trying to redefine CC and ASM for gcc.cmake.

Could you please update readme.

**Comment by mikisama** [comment]
Hi, @AntonKukoba1 

Good suggestion, Thanks!
